name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy_url.outputs.url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Set up application
        run: |
          cp .env.production .env
          php artisan key:generate
          echo "MAIL_PASSWORD=\"${{ secrets.MAIL_PASSWORD }}\"" >> .env

      - name: Install Npm Dependencies
        run: |
          npm install
          npm run build

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Set deploy URL
        id: deploy_url
        run: echo "url=https://your-app-url.com" >> $GITHUB_OUTPUT
